### PR TITLE
Feat/update example and build config

### PR DESCRIPTION
**Pull request by karltaylor**
Quite a while ago now I created a branch for a new release for version `3.0.0` but unfortunately as time went on it kind of got outdated.

I've taken the base architecture from that which is only the build process and example but sets us up for any future improvements.

In a nutshell

- Removes the need for `webpack-dev-server` for the example and replaces it with [parceljs](https://parceljs.org/).
- Uses a simple `webpack.config.js` file to build the main library.
- Uses `@babel/plugin-proposal-class-properties` to use arrow functions in classes and remove the need for binding in the constructor.
- Adds a `.prettierrc` to keep formatting consistent

There is 1 thing that I would like to double-check, in `package.json` I have changed the `main` entry point.

Previously it was

```json
"main": "dist/Collapsible.js",
```

and now it is

```json
"main": "dist/index.js",
```

And I _think_, if people import it like so (no idea why they would), it would break. But realistically, you shouldn't be importing a module like this anyway.

```js
import Collapsible from "node_modules/react-collapsible/dist/Collapsible.js"
```

For this reason, it might be a breaking change, however, since this PR is mainly internal/chore related, I do think we could merge this to develop, and deal with the semver change when we need to do a release.

### CODE REVIEW

**Comment by karltaylor** [comment]
Hey @glennflanagan good to get your thoughts on this

**Comment by glennflanagan** [comment]
This all look sensible to me - if you want to check whether it's a breaking change before merging it in you can publish it to npm as a release candidate or a beta and then try npm installing it in another project. You also have conflicts now which you'll want to resolve.

**Comment by karltaylor** [comment]
Hey @glennflanagan thanks, few more updates:

- Fixed the conflicts
- Fixed the tests
- Added github actions for tests in the future

I also installed via git URL using yarn and works absolutely fine. Happy to say this is just a minor version bump up to `2.9.0`. Shall I put this version change in this PR or wait until we've merged it to develop?

**Comment by karltaylor** [comment]
Hey @glennflanagan, happy holidays! 🎄  Are you happy for this to be merged?

**Comment by glennflanagan** [comment]
Yes I am. Sorry! Happy Holidays to you too

**Pull request merged**
