### PR TITLE
Feature/add eslint

### PR DESCRIPTION
**Pull request by karltaylor**
Adding basic eslint rules.

• always semi colons
• indent 2 spaces

### CODE REVIEW

**Comment by glennflanagan** [comment]
I have a feeling this is going to be a tabs-vs-space debate, except with semi-colons. I prefer semicolons being present as it makes it much easier to scan where the end of the line is when an expression is over several lines.

e.g. I find this easier to scan
```
const someVar = someArray
  .map(m => m.id)
  .filter(m => m !== 1)
  .filter(m => m !== 'x');
  someOtherArray
  .forEach(m => m.somefunc())
  .forEach(m => m.someOtherFunc())
  .forEach(m => m.someOtherFuncAgain())
  .forEach(m => m.somefunc());
```

than this

```
const someVar = someArray
  .map(m => m.id)
  .filter(m => m !== 1)
  .filter(m => m !== 'x')
  someOtherArray
  .forEach(m => m.somefunc())
  .forEach(m => m.someOtherFunc())
  .forEach(m => m.someOtherFuncAgain())
  .forEach(m => m.somefunc())
```

**Comment by karltaylor** [comment]
@glennflanagan no problem! That's why I did the PR just to double check your preferences. I'll update and push :)

**Comment by karltaylor** [comment]
GTM? 😊

**Comment by glennflanagan** [comment]
All good. Sorry, busy day at work!

**Pull request merged**
