### PR TITLE
Fixed issue where passing a component to triggerSibling was failing in React

### PR DESCRIPTION
**Pull request by trevlar**
…n React.

### CODE REVIEW

**Comment by trevlar** [comment]
@glennflanagan When I was passing a component into triggerSibling I was getting an error from React. With this fix it works without any errors. Please review, test and merge my change.

Cheers!

**Comment by trevlar** [comment]
Without this fix I saw the following error in the console while running a react app that was using react-collapsible. 

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

    Check the render method of `Collapsible`.
```

**Comment by karltaylor** [comment]
I can see the issue here, I just need to think about how to fix it since it would be breaking change.

If we remove the brackets: `return this.props.triggerSibling`

You then need to **call** the triggerElement: 

```jsx
<Collapsible trigger={'hi'} triggerSibling={triggerSiblingExample()}>
```

But this allows you to pass in a React component rather than a functional component.

```jsx
<Collapsible triggler={'hi'} trigglerSibling={<TrigglerSiblingExample/>}>
```

What we could do so it's not a breaking change is just check if we're passing in a function, string or object (React Class Component). So it renders all three correctly.

@glennflanagan / @rsarai does this make sense to you guys?

**Comment by glennflanagan** [comment]
I'll be honest I don't fully understand the issue. @trevlar are you able to create a JSFiddle with an example of it failing?

**Comment by karltaylor** [comment]
https://jsfiddle.net/te1ej1wt/ Here you go -

React Components passed in the trigglerSibiling Prop as `<Component />` do not work unless we check for the prop type being passed e.g: string, function, or react component (object?).

**Comment by karltaylor** [comment]
Although, you can still pass in a function which just returns the React.Component?

@trevlar isn't this ok? Or is it basically just creating two functions? Might not be a good way of doing it but a work around for now.

```jsx
  <Collapsible trigger={"React Components don't work"} triggerSibling={() => <TriggerSibling />}>
    <p>You won't see me.</p>
   </Collapsible>
```

**Comment by glennflanagan** [comment]
That would work as a workaround for now as it would allow you to add any props to that component. 👍

**Comment by karltaylor** [comment]
Going to leave this for now as it doesn't really affect perf / filesize

**Pull request closed without merging**
