### PR TITLE
feat: add triggerElementProps to allow passing of props to trigger element

### LINKED ISSUE #146: Be able to set custom properties on trigger element
**Describe the bug**

When running accessibility audits using [axe pro](https://axe.deque.com) and enabling tab index, it was noted that there is no role on the Trigger element. 

This lead to us realising that there is no way of passing props to the trigger element. In our case, this would be for aria roles and labels. 

**To Reproduce**

Try and pass properties to the trigger element

**Expected behaviour**
There should be some way of setting additional properties on the trigger element. As there is already a containerElementProps prop, it would be nice to have a triggerElementProps prop on the Collapsible. This would allow the passing of an object that would set props on the TriggerElement

I'm happy to raise a PR for this if you would like

### PR DESCRIPTION
**Pull request by MattBodey**
This PR fixes #146 by allowing the user to pass a new prop to the component.

### CODE REVIEW

**Comment by karltaylor** [comment]
Thanks Matt, this works great. CC @glennflanagan 

What do you think about throwing a warning/error if a user tries to pass `className` to `triggerElementProps`?

If they do, the collapsible styling + functionality will break.

Perhaps in 

```js
componentDidMount() {
  const { triggerElementProps } = this.props
  if (triggerElementProps && triggerElementProps.className) {
    console.warning('Cannot pass className to triggerElementProps')
   // or explicitly, (People using CRA would have a visual error if they're using the overlay)
   throw new Error('Cannot pass className to triggerElementProps')
  }
}
```

**Comment by glennflanagan** [comment]
@karltaylor if the className is required then we should spread the `className` into the `triggerElementProps` object to ensure it's there, or even better still, merge the two `className`s

**Comment by karltaylor** [comment]
We have the prop `triggerClassName` already though so we would be getting a prop from two different locations so it might start to get a bit complicated

**Comment by karltaylor** [comment]
To be honest,

We already do this here:

```js
<ContentContainerElement className={parentClassString.trim()} {...this.props.containerElementProps}>
```

I guess we can leave it to the user to understand not to pass the className into this prop as it will break stuff?

**Comment by karltaylor** [comment]
I'm happy to merge 🎉🚀

@MattBodey thanks for creating an itch to work on this over the weekend 👍 😅

**Comment by glennflanagan** [comment]
Agreed, this is something that can be avoided by dev config so we don't need to overcomplicate the code even more

**Comment by MattBodey** [comment]
Thanks! 

I think that merging the className would be a good idea, though I hope that by the time someone is injecting custom props they understand what they are doing somewhat 😄

**Pull request merged**
